plugins:
  - '@dotcom-tool-kit/circleci-npm'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/secret-squirrel'
  - '@dotcom-tool-kit/webpack'

hooks:
  'test:local':
    - 'Eslint'
  'test:ci':
    - 'Eslint'
  git:precommit:
    - SecretSquirrel
    - LintStaged
  'build:local':
    - WebpackDevelopment

options:
  '@dotcom-tool-kit/webpack':
    configPath: demos/webpack.config.js
  '@dotcom-tool-kit/prettier':
    files: ['{,!(node_modules|demos/public)/**/}*.js']

